INPUT:
  MIN_DIM: 736
  MAX_DIM: 1248
  NUM_CLASSES: 2
  NUM_FRAMES: 16
MODEL:
  EMBEDDING_DIM_MODE: "xyff"
  USE_SEEDINESS_HEAD: true
  USE_SEMSEG_HEAD: false
  EMBEDDINGS:
    EMBEDDING_SIZE: 4
TRAINING:
  MODE: "davis"
  FREEZE_BACKBONE: true
  INITIAL_LR: 0.001
  LR_DECAY_TYPE: "none"
  MAX_ITERATIONS: 10000
  LOSSES:
    EMBEDDING:
      FREE_DIM_STDS: [0.3, 0.3]
DATA:
  YOUTUBE_VIS:
    FRAME_GAP_LOWER: 16
    FRAME_GAP_UPPER: 16