INPUT:
  MIN_DIM: 736
  MAX_DIM: 1248
  NUM_CLASSES: 2
  NUM_FRAMES: 8
MODEL:
  EMBEDDING_DIM_MODE: "xyff"
  USE_SEEDINESS_HEAD: true
  USE_SEMSEG_HEAD: false
  EMBEDDINGS:
    EMBEDDING_SIZE: 4
TRAINING:
  MODE: "davis"
  INITIAL_LR: 0.001
  LR_DECAY_TYPE: "exponential"
  LR_EXP_DECAY_FACTOR: 0.1
  LR_EXP_DECAY_START: 40000
  LR_EXP_DECAY_STEPS: 10000
  MAX_ITERATIONS: 50000
  LOSSES:
    EMBEDDING:
      FREE_DIM_STDS: [0.3, 0.3]