INPUT:
  MIN_DIM: 640
  MAX_DIM: 1196
  NUM_CLASSES: 41
  NUM_FRAMES: 8
MODEL:
  EMBEDDING_DIM_MODE: "xyff"
  USE_SEEDINESS_HEAD: false
  USE_SEMSEG_HEAD: true
  EMBEDDINGS:
    EMBEDDING_SIZE: 4
  SEMSEG:
    INTER_CHANNELS: [256, 256, 256, 256]
TRAINING:
  MODE: "youtube_vis"
  INITIAL_LR: 0.001
  LR_DECAY_TYPE: "exponential"
  LR_EXP_DECAY_FACTOR: 0.01
  LR_EXP_DECAY_START: 60000
  LR_EXP_DECAY_STEPS: 100000
  MAX_ITERATIONS: 160000
  LOSSES:
    EMBEDDING:
      FREE_DIM_STDS: [0.3, 0.3]